# Generated by Django 4.1.7 on 2023-04-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderCL',
        ),
    ]
